services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - PORT=${PORT}
    command:
      [
        sh,
        -c,
        "cd /app && echo $DATABASE_URL && npx prisma db push && npx prisma generate&& npm i @nestjs/cli && npm run build && npm run start:prod"
      ]
    ports:
      - '4400:4400'
    env_file:
      - .env
    restart: always
    depends_on:
      - redis

  nextjs-app:
    image: bekshoyatbekov/nextjs-app:1.0.9
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - nextjs-data:/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  nextjs-data:
  redis-data:
