services:
  app:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4400:4400'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/oar
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    
  redis: 
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
